export { default as SectionTitleH1 } from './SectionTitleH1'
export { default as SectionTitleH2 } from './SectionTitleH2'
export { default as DisplayBodyH2 } from './DisplayBodyH2'
export { default as CardTitleH3 } from './CardTitleH3'
export { default as H5 } from './h5'
export { default as BodyStylised } from './BodyStylised'
export { default as Paragraph } from './p'
