export { default as SectionTitleH1 } from './SectionTitleH1'
export { default as SectionTitleH2 } from './SectionTitleH2'
export { default as DisplayTitleH2 } from './DisplayTitleH2'
export { default as CardTitleH3 } from './CardTitleH3'
export { default as SubtitleH3 } from './SubtitleH3'
export { default as BodyStylised } from './BodyStylised'
export { default as Paragraph } from './p'
