module.exports = ({ overwrite }) => ({
  created: 1567435659000,
  duration: 7200000,
  id: '264495985',
  name: 'London Tensorflow Meetup - #11',
  rsvp_limit: 80,
  date_in_series_pattern: false,
  status: 'upcoming',
  time: 1569949200000,
  local_date: '2019-10-01',
  local_time: '18:00',
  updated: 1569247585000,
  utc_offset: 3600000,
  waitlist_count: 0,
  yes_rsvp_count: 61,
  venue: {
    id: 26167139,
    name: 'YLD',
    lat: 51.520877838134766,
    lon: -0.09776300191879272,
    repinned: true,
    address_1: '124 Aldersgate St',
    city: 'London',
    country: 'gb',
    localized_country_name: 'United Kingdom'
  },
  group: {
    created: 1473070024000,
    name: '#LTM — London TensorFlow Meetup',
    id: 20389720,
    join_mode: 'open',
    lat: 51.52000045776367,
    lon: -0.10000000149011612,
    urlname: 'London-TensorFlow-Meetup',
    who: "TensorFlow'ers",
    localized_location: 'London, United Kingdom',
    state: '17',
    country: 'gb',
    region: 'en_US',
    timezone: 'Europe/London'
  },
  link: 'https://www.meetup.com/London-TensorFlow-Meetup/events/264495985/',
  description:
    '<p>Hi Everyone,</p> <p>We’re happy to announce we’re back with an October meetup!</p> <p>We already have two speakers confirmed:</p> <p>1) Daniel Hulme (@thesolveengine) - CEO @ Satalia<br/>"AI and the Future of Business"</p> <p>2) Tom Gallacher (@tomgco ) - Staff Engineer @ YLD</p> <p>More information to come soon!</p> <p>---------</p> <p>Thank you to our sponsors:</p> <p>YLD<br/><a href="https://twitter.com/YLDio" class="linkified">https://twitter.com/YLDio</a></p> <p>YLD is one of London’s fastest growing software engineering consultancies building exciting products and platforms in React / Node for Trainline, Vogue, The Economists and many more. The team is committed the open source community aiming to create a long standing engineering culture and delivery capability in each piece of work.</p>',
  visibility: 'public',
  member_pay_fee: false,
  ...overwrite
})
