module.exports = {
    created: 1529495355000,
    duration: 9000000,
    id: '251946999',
    name: 'ReactJS Girls #11 -  Reason, the good, the bad and ugly bits',
    rsvp_limit: 120,
    status: 'upcoming',
    time: 1531846800000,
    local_date: '2018-07-17',
    local_time: '18:00',
    rsvp_close_offset: 'PT29H',
    updated: 1529501391000,
    utc_offset: 3600000,
    waitlist_count: 0,
    yes_rsvp_count: 81,
    venue: {
        id: 25864764,
        name: 'JP Morgan',
        lat: 51.512203216552734,
        lon: -0.1062759980559349,
        repinned: false,
        address_1: '4 John Carpenter St',
        city: 'London',
        country: 'gb',
        localized_country_name: 'United Kingdom'
    },
    group: {
        created: 1503484690000,
        name: 'React.JS Girls London',
        id: 25597475,
        join_mode: 'open',
        lat: 51.52000045776367,
        lon: -0.10000000149011612,
        urlname: 'ReactJS-Girls-London',
        who: 'ReactJS Girls',
        localized_location: 'London, United Kingdom',
        region: 'en_US'
    },
    link: 'https://www.meetup.com/ReactJS-Girls-London/events/251946999/',
    description: `<p>Welcome to ReactJS Girls #11 meetup!</p> <p>We're super excited to bring you another ReactJS Girls meetup on the July 17 (and the last one before the summer break).</p> <p>Thanks to YLD for organising and JP Morgan for hosting.</p> <p>EVENT SUMMARY:<br/>Kara Stubbs (@kiraarghy), a Software Engineer at MOO, talks about her experience with React and ReactReason.</p> <p>EVENT DETAILS</p> <p>1) Kara Stubbs (@kiraarghy) - Software Engineer at MOO</p> <p>*Reason, the good, the bad and the ugly bits*</p> <p>Reason and ReasonReact are a much-hyped solution to the ever-increasing complexity of modern JS and React codebases. As a recent beginner to the syntax, I will share the hard things I've learned on the way, introduce you to the exciting new programming paradigms it provides to React, and hopefully get you interested in Reason!</p> <p>2) Second talk to be announced soon</p> <p>______________</p> <p>Thank you to our sponsors:</p> <p>YLD<br/><a href="https://twitter.com/YLDio" class="linkified">https://twitter.com/YLDio</a></p> <p>YLD is one of London’s fastest growing software engineering consultancies building exciting products and platforms in React / Node for Trainline, Vogue, The Economists and many more.</p> <p>The team is committed the open source community aiming to create a long-standing engineering culture and delivery capability in each piece of work.</p> <p>YLD is looking for React / Node / Devops engineers to join the team: <a href="https://jobs.lever.co/yld" class="linkified">https://jobs.lever.co/yld</a></p> <p>Watch Tech Talks YLD youtube channel for more talks on React and Node:<br/><a href="https://www.youtube.com/TechTalksYLD" class="embedded">https://www.youtube.com/TechTalksYLD</a></p> <p>Join the conversation:<br/>- Twitter @YLDio (<a href="https://twitter.com/YLDio" class="linkified">https://twitter.com/YLDio</a>)<br/>- LinkedIn (<a href="https://www.linkedin.com/company/yld" class="linkified">https://www.linkedin.com/company/yld</a>)</p> <p>---------</p> <p>JP Morgan<br/><a href="https://twitter.com/JPMorgan" class="linkified">https://twitter.com/JPMorgan</a></p> <p>J.P. Morgan is a global leader in financial services, offering solutions to the world's most important corporations, governments and institutions in more than 100 countries. The Firm and its Foundation give approximately US$200 million annually to nonprofit organizations around the world. We also lead volunteer service activities for employees in local communities by utilizing our many resources, including those that stem from access to capital, economies of scale, global reach and expertise.</p> <p>__________________________________</p> <p>Looking forward to seeing you soon,<br/>#ReactJSGirls</p>`,
    visibility: 'public',
    ratelimit: { limit: '30', remaining: '28', reset: '10' }
};
