name: Clean Spaces

on:
  schedule:
    - cron: '30 23 * * *'

jobs:
  clean-spaces:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Setup Yarn Cache
        uses: actions/cache@v3
        with:
          path: |
            .yarn
            node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Cleanup spaces
        run: yarn clean-up-test-spaces
        if: always()
        env:
          CONTENTFUL_INTEGRATION_TEST_CMA_TOKEN: ${{ secrets.CMS_CRUD }}
